### ISSUE TITLE
Test-Function

### ISSUE THREAD

**Issue by ThomasKnecht** [krlmlr/SwissHistMunData#2] opened 2019-09-30 13:56 UTC
Do i get it right, that the test_that function fails if the data is not identical? That means, that the data is not overwritten... 

I work at the tic.R file and I was thinking about the following steps:
1. Test if the downloaded data is identical (with identical(x,y)); 
If identical(x,y) == FALSE, the following steps are made:
      1. overwrite the data
      2. Bump up the version 
2. add_package_check 

The identical check and the overwriting should be separate.
That means that the test_that-function should rather check if there is data after the step 1.i.

**Comment by krlmlr** [comment] 2019-09-30 14:40
This sounds about right. Maybe it would help to move the data import stage away from the tests?

Is this issue a duplicate of #1?

**Comment by ThomasKnecht** [comment] 2019-09-30 15:00
True, we can discuss that under #1.

**Closed as completed** 2019-10-01 08:57 UTC
